steps:
  - label: ":bathtub: Lint"
    key: "lint"
    command: ".buildkite/lint.sh"
    agents:
      image: "golangci/golangci-lint:v1.55.2"

  - label: ":test_tube: Test"
    key: "test"
    command: ".buildkite/test.sh"
    agents:
      image: "golang:1.21.6-bookworm"
